# Adapted from
# https://docs.haskellstack.org/en/stable/travis_ci/

sudo: required
dist: trusty

language: minimal

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  timeout: 600

matrix:
  include:
  - env: BUILD=integration ARGS=""
    compiler: ": #integration default"

  - env: BUILD=integration RESOLVER_SERIES=lts-9 ARGS="--resolver lts-9 --stack-yaml stack-travis.yaml"
    compiler: ": #integration LTS 9"

  - env: BUILD=integration RESOLVER_SERIES=lts-10 ARGS="--resolver lts-10 --stack-yaml stack-travis.yaml"
    compiler: ": #integration LTS 10"

  - env: BUILD=integration RESOLVER_SERIES=lts-11 ARGS="--resolver lts-11"
    compiler: ": #integration LTS 11"

  - env: BUILD=integration RESOLVER_SERIES=lts-12 ARGS="--resolver lts-12"
    compiler: ": #integration LTS 12"

  - env: BUILD=integration RESOLVER_SERIES=lts-13 ARGS="--resolver lts-13"
    compiler: ": #integration LTS 13"

  - env: BUILD=integration RESOLVER_SERIES=lts-14 ARGS="--resolver lts-14"
    compiler: ": #integration LTS 14"

  - env: BUILD=npm
    compiler: ": #npm"

before_install: source ./travis/before_install

install: source ./travis/install

script: source ./travis/build

deploy:
  provider: script
  script: ./travis/deploy
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition:
      - '$BUILD = stack'
      - '$ARGS = ""'
      - '$(uname) = Linux'
      - '$TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$'
