resolver: lts-20.26 # ghc 9.2.8
packages:
  - .
  - example-project
nix:
  packages:
    - zlib.dev
    - zlib.out
# Work around https://github.com/commercialhaskell/stack/issues/5290
save-hackage-creds: false
extra-deps:
  - crypton-0.33@sha256:5e92f29b9b7104d91fcdda1dec9400c9ad1f1791c231cc41ceebd783fb517dee,18202
  - github: brendanhay/amazonka
    # Amazonka 2.0.0-rc2 TODO switch to hackage dependency once 2.0 is released
    commit: 31f3d044d84912b99e396a97085a9678e699d91f
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-sts # amazonka library depends on this
      - lib/services/amazonka-kinesis
      - lib/services/amazonka-s3
