resolver: lts-18.8
packages:
  - .
  - example-project
nix:
  packages:
    - zlib.dev
    - zlib.out
# Work around https://github.com/commercialhaskell/stack/issues/5290
save-hackage-creds: false
extra-deps:
  - github: brendanhay/amazonka
    commit: e4fdf4a33e357942a6bc5bb6bfc133f18b56fa0c
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-sts # amazonka library depends on this
      - lib/services/amazonka-kinesis
      - lib/services/amazonka-s3
