name: shtest
version: 0.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- serverless-haskell

executables:
  main:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  apigw:
    main: ApiGateway.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - lens
      - text
      - unordered-containers
