name: Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Stack
        run: stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set up cache
        uses: actions/cache@v1
        with:
          key: deploy
          path: ~/.npm
      - name: Deploy
        run: ./deploy
        env:
          HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
